apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
  name: family-neha
  namespace: family
spec:
  rules:
  - host: family-neha.k8s1.bjethwan.xyz
    http:
      paths:
      - backend:
          serviceName: neha
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: neha
  namespace: family
spec:
  type: ClusterIP
  selector:
    name: neha
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neha
  namespace: family
spec:
  replicas: 1
  selector:
    matchLabels:
      name: neha
  template:
    metadata:
      labels:
        name: neha
    spec:
      containers:
      - name: bipin
        image: nginx
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: html
          configMap:
            name: neha
            items:
              - key: message
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neha
  namespace: family
data:
  message: "<h1 style=\"color:Tomato;\"> Neha Talreja Jethwani</h1>"

